apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: challenge
spec:
  type: NodePort
  ports:
    - name: enduser
      port: 80
      targetPort: enduser
  selector:
    deployment: hello
